### PR TITLE
Add PHP 8 support

### PR DESCRIPTION
**Pull request by osbre**
[All tests passed](https://github.com/osbre/html-element/actions), as you can see from the "Actions" section on my fork repository page.

### CODE REVIEW

**Comment by osbre** [comment]
@sebastiandedeyne Should I drop 7.3, 7.4 and keep only PHP 8?

**Comment by freekmurze** [comment]
Keep those old versions around for now. We'll soon create a new major version which will drop support for PHP 7.

**Comment by osbre** [comment]
> which will drop support for PHP 8

@freekmurze So you're going to deprecate this package? Or I misunderstood something? 

**Update:**  Sorry. Most likely, the meaning was "which will drop support **in favor of** PHP 8"

**Comment by freekmurze** [comment]
Updated my comment 🙂

**Comment by sebastiandedeyne** [comment]
Thanks!

**Pull request merged**
